import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import ThemeToggle from "./components/ThemeToggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="top-bar">
          <nav className="top-bar-nav" aria-label="Primary">
            <Link href="/" className="top-bar-link">
              Home
            </Link>
            <Link href="/domains" className="top-bar-link">
              Domains
            </Link>
            <Link href="/captions" className="top-bar-link">
              Captions
            </Link>
            <Link href="/generate-captions" className="top-bar-link">
              Generate Captions
            </Link>
          </nav>
        </header>
        <div className="theme-toggle-float">
          <ThemeToggle />
        </div>
        {children}
      </body>
    </html>
  );
}
